### PR TITLE
New 'players' and 'filter' options

### PR DESCRIPTION
**Pull request by Spongecade**
'players' option: Creates new game with users included in the 'players' value being the only players
'filter' option: Allows you to define who can join a game through a function

### CODE REVIEW

**Comment by SimonLeclere** [comment]
Hey, this code is much better than your previous PR congratulations :)

Concerning the players option, I don't have much to say except that it could be interesting to be able to take both an array of id and an array of users.

Then as for the allow option I'm rather reserved. I think that a filter option would be better because it would allow the user to define his own rules, like for example "only certain roles can participate" or "all those who have a nickname longer than 10 characters can participate" (not very useful but it's an example haha)
Also in case a user doesn't meet meet the criteria, it may be worth sending or not a customizable message.

If you need help with my suggestions do not hesitate to ask me I will help you with pleasure!

Have a nice day,
Simon.

**Comment by Spongecade** [comment]
>Hey, this code is much better than your previous PR congratulations :)

:)

I think the 'players' option is fine as is. With the 'allow' option, it is a filter and only allows certain players to be able to join the game. Excerpt from my changes to gettingstarted.md ↓
```js
let allowed = message.guild.roles.cache.get('ROLEID').members.map(m => m.user)

hangman.create(message.channel, 'random', {allow: allowed})
```
This allows only people with the roleid, able to respond to the join message and be counted. You can change the 'allowed' variable to lot's of different things and can combine variables together in an array. But, since usually most people look to roles to filter such an option. I might change the allow option to be a role option as that would make writing a custom gatherPlayersMsg easier. But I guess with the allow option, you could create a custom join message somehow.

Let me know if there is any confusion regarding your statement about the 'allow' option

**Comment by SimonLeclere** [comment]
I meant that the allow option should be renamed as "filter" and should be a function.

For example : 
```js
​hangman​.​create​(​message​.​channel​,​ ​'random'​,​ ​{​ filter: (msg) => FUNCTION HERE }​)
```

**Comment by Spongecade** [comment]
oh ok thanks for clearing it up. I'll be changing the gettingstarted.md and the code soon. I have this pushed back a bit to focus and some school work. Thank you!

**Comment by SimonLeclere** [comment]
No problems thanks for your work :)

**Comment by Spongecade** [comment]
Not starting the filters option now but, is this **very quick** outline what you had in mind?
```js
    hangman.create(message.channel, 'random', { filters : (step) => {
            if (step === 'collectreaction') { // Triggered in #gatherPlayersFromReaction filter const
                // Your code here
                return // filter value #gatherPlayersFromReaction
            }
            if (step === 'collectmessage') { // Triggered in #gatherPlayersFromMessage filer const
                // Your code here
                return // filter value for #gatherPlayersFromMessage
            }
        }
    })
```

**Comment by SimonLeclere** [comment]
This is what I had in mind:
```js
hangman.create(message.channel, 'random', { filter: member => member.roles.cache.find(role => role.name === 'hangman') })
```

**Comment by Spongecade** [comment]
oh  …lol ok. I'll wrap this request up when I can.

**Comment by Spongecade** [comment]
Let me know what you think of the code. Example of filter option ↓
```js
    hangman.create(message.channel, 'random', {
        filter: member => {return member.roles.cache.has("ROLEID")}
        }
    )
```

**Comment by SimonLeclere** [comment]
Yup seems good

**Comment by Spongecade** [comment]
> Yup seems good

Nice!
I'll just update the gettingStarted.md file and then I'll send it for review

Thank you!

**Comment by Spongecade** [comment]
Sorry for the commit mess...

**Comment by SimonLeclere** [comment]
No problems haha

**Comment by Spongecade** [comment]
Alright I'm all done now... phew

**Comment by Spongecade** [comment]
I'm ready for the code to be merged. Let me know if you want me to change anything.
Or just ask me questions about the code.

**Comment by SimonLeclere** [comment]
I changed your code a little bit to fit the style of the project, tell me what you think and if everything is good I'll merge the pull request! :)

**Comment by Spongecade** [comment]
I just had to change one thing and that was to remove '!u.bot' and 'filter(u)' from `gatherFilter` in gatherPlayersFromReaction. I had to do this because awaitReactions, only waits for one person to pass the filter and then `collected.first().users.cache.forEach`  pushes **everyone else** that reacts to the message to the player array (even ones that are bots and ones that don't pass the filter) So, I put them down by  `collected.first().users.cache.forEach` 
Besides that, everything is good! Ready to merge!

**Comment by SimonLeclere** [comment]
Okay, maybe we can avoid this problem by using a reaction collector (like for messages)? What do you think?

**Comment by Spongecade** [comment]
Yeah it would be more flexible to add a reaction collector... I'll add that real quick...

**Comment by SimonLeclere** [comment]
Okay perfect

**Comment by Spongecade** [comment]
With that, we should be good to go! ..sorry for the delay

**Comment by SimonLeclere** [comment]
Seems very good to me, I'll merge it !
If you have other ideas, don't hesitate to make another pull request or to tell me about it on discord :)

**Comment by Spongecade** [comment]
Thank you! You were very helpful through every step of this PR!
I have another idea in mind that I might add in the future...

Thank you again!

**Pull request merged**
