### PR TITLE
Quick fix to reaction collector

### PR DESCRIPTION
**Pull request by Spongecade**
Fixed a little oversight with the reaction collector... Now players who un-react to the join message, will not be in the game (which did not happen previously)

### CODE REVIEW

**Comment by SimonLeclere** [comment]
Hey, thanks for your work (I didn't think of that haha), can you just use a filter() to remove the player from the array?

Something like that should work:
```js
players = players.filter(p => p.id !== u.id)
```

Apart from that I have no other suggestions and I am ready to merge :)

**Comment by Spongecade** [comment]
Thanks for the nice little suggestion. Sorry for the delay again (I summited this during a passing period.) Updated the file, good to go!

**Comment by SimonLeclere** [comment]
Nice thanks a lot

**Comment by Spongecade** [comment]
No problem :)

**Pull request merged**
