### PR TITLE
New 'players' option --Reworked Above--

### PR DESCRIPTION
**Pull request by Spongecade**
I created a new gamemode called 'quickstart'. Because there was no way to automatically start a game and just have the message author be the player, (essentially there was no quick single-player mode) I made one myself!

### CODE REVIEW

**Comment by SimonLeclere** [comment]
Hey, I looked at your pull request, the idea is good! 
Nevertheless your code has some inconsistencies: 
- Why take message and message.channel as parameters when you can get the channel in the message object?
- Some lines are doubled which makes the function longer
- Why is the custom word option ignored?
To improve your pull request (and before I merge it), I advise you either to make a quickStart function apart from the start function, or to add a players option containing the list of players, which would allow users to retrieve the players by their own means (and in particular via the message.author)

**Comment by Spongecade** [comment]
Yeah I had the quickstart it's own function but decided to merge it into the create function for it to be easier to explain on the gettingstarted.md. I'll update the code

**Comment by Spongecade** [comment]
I'm kind of glad I got lazy (sorry I was pretty anxious to send this PR) and just put what was originally the quickstart function into the create() function. Because your suggestion to add a player option really hit home to me. I'll be working on that suggestion. Here is what I'm aiming for

- Auto start game with message author as the only player
- Auto start game with other players (ie: players with certain roles)
- Have only certain people be able react or type "join" to join game

I'll be working on this for the next couple of days

**Comment by SimonLeclere** [comment]
Hey, did you give up your pull request or are you planning to make another one?

**Comment by Spongecade** [comment]
I'm planning to make another one in the near future...

**Comment by SimonLeclere** [comment]
Okay cool :)

**Pull request closed without merging**
